package edu.yorku.sneaker_store_backend.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Entity class representing a sneaker product in the system.
 * This class is mapped to the "sneaker" table in the database.
 */
@Entity
@Table(name = "sneakers")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Sneaker {

    /**
     * Primary key, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the sneaker, e.g., "Air Jordan 1".
     * Cannot be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Brand of the sneaker, e.g., "Nike", "Adidas".
     */
    @Column(nullable = false)
    private String brand;

    /**
     * Colorway of the sneaker, e.g., "Bred", "Triple White".
     */
    private String colorway;

    /**
     * Retail price of the sneaker.
     */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal price;

    /**
     * Number of items available in stock.
     */
    private Integer stock;

    private String category;

    private String genre;

    /**
     * Available shoe sizes for this sneaker (e.g., "8", "9.5").
     */
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "sneaker_sizes", joinColumns = @JoinColumn(name = "sneaker_id"))
    @Column(name = "size", length = 10)
    @Builder.Default
    private List<String> availableSizes = new ArrayList<>();

    /**
     * Long description used for product detail pages.
     */
    @Column(length = 1000)
    private String description;

    /**
     * URL pointing to the product image hosted online.
     */
    private String imageUrl;

    /**
     * Ensures the available sizes list never remains null while still allowing callers to replace
     * the collection wholesale.
     */
    public void setAvailableSizes(List<String> availableSizes) {
        this.availableSizes = availableSizes != null ? new ArrayList<>(availableSizes) : new ArrayList<>();
    }
}
